version: "3.9"
services:
  flask-api:
    build: .
    container_name: flask-micro-api-container
    ports:
      - "5000:5000"
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
